sensors: Handle error sentences from sensors
Amdgpu drivers produces an output that cannot be handled by sensors:

root@qt5222:~# sensors -A -u
amdgpu-pci-0300
vddgfx:
ERROR: Can't get value of subfeature in0_input: Can't read
vddnb:
ERROR: Can't get value of subfeature in1_input: Can't read
edge:
  temp1_input: 40.000
  temp1_crit: 80.000
  temp1_crit_hyst: 0.000

00000400100-mdio-4
temp1:
  temp1_input: 59.000
  temp1_crit: 100.000
  temp1_max_alarm: 0.000

This results in an invalid parsing of its ouput. Eg:

> sensors,chip=ERROR:\ Can't\ get\ value\ of\ subfeature\ in0_input:\ Can't\ read,feature=isl_curr_soc,host=qt5222,serial=${SERIAL_NUMBER} curr_input=1.6 1592920794000000000

The invalid parsing is due to the different buffer size of stdout and
stderr. Which results on stderr output out of sync with stdout.

Since we do not need the output of stderr, simply ignore it.

Signed-off-by: Ricardo Ribalda <ricardo@ribalda.com>